### PR TITLE
upsert instead of insert to allow for subsequent runs without duplicating data

### PR DESCRIPTION
**Pull request by seiyria**
this means that if you accidentally re-run the crawler it will only add new apps that it finds instead of naviively inserting them.

same with the app data worker.

### CODE REVIEW

**Comment by seiyria** [comment]
this will resolve #26, also.

**Comment by seiyria** [comment]
hey, sorry, this actually broke the build - I'm working on fixing it right now.

would you mind setting up travis CI to run a check to make sure the app builds so a PR can at least be guaranteed to build? http://docs.travis-ci.com/user/languages/csharp/ is a good guide to getting started

thanks!

**Comment by MarcelloLins** [comment]
That's OK !

I haven't played with Travis CI yet, how does it work ?

Will it check for build errors prior to each commit ?

**Comment by seiyria** [comment]
Basically, Travis will run on each push (either your push, or a PR push) and make sure the code builds based on the standards you have. Basic standards would be to just check if the application still builds, but you can also add style checking, etc in and do what you need to there.




Where you normally see this, you'll instead see Travis pending, and if Travis succeeds, it will still be a green checkmark. Otherwise, it'll be a red x marking failure to pass the build.

**Pull request merged**
